Litt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


admin.site.site_header = "LITT AdminPanel"
admin.site.site_title = "Litt App Admin "
admin.site.site_index_title = "Welcome To Litt Admin Panel"

core/urls.py
# from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
# from .views import HomeView
from . import views

app_name = 'core'

urlpatterns = [
    # path('', HomeView.as_view(), name='home'),
    path('', views.index, name='index',),
    path('Home', views.home, name='home'),
    path('category/', views.category, name='category'),
    path('category/<slug>', views.category_detail, name='category_detail'),
    path('albums/', views.album, name='album'),
    path('albums/<slug>', views.album_detail, name='album_detail'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('pricing/', views.pricing, name='price'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('success/', views.send_success, name='send_success'),

]

core/forms.py
from django import forms

from .models import Upload


class UploadForm(forms.Form):
    class Meta:
        model = Upload
        fields = '__all__'


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField(required=True)
    subject = forms.CharField()
    # phone = forms.CharField()
    message = forms.CharField(required=True, widget=forms.Textarea(
        attrs={'placeholder': 'Enter Message Here', 'cols': "2", 'rows': "2",
               'class': ''}))

templates/base.html
<!doctype html>
{% load static %}
{% load instagram_client %}
<html class="" lang="">
<!-- InstanceBegin template="/Templates/page-full-width.dwt" codeOutsideHTMLIsLocked="false" -->

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> THE LITT PHOTOGRAPHER{% block title %}

    {% endblock %}</title>

    <!-- FAV and TOUCH ICONS -->
    <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'logo.png' %}"/>

    <!-- FONTS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts/montserrat/montserrat.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic' rel='stylesheet'
          type='text/css'>

    <!-- STYLES -->

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts/fontello/css/fontello.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slippry/1.4.0/slippry.min.css"
          integrity="sha512-T+a5Aa01HOiiskCpZYtRZu69nfOIyhjrDn0PRClEQTDKZ16pcdvaU7KD1m0NrQIKn6LqUzY8tgLsfOVGiJs2Rg=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fluidbox/2.0.5/css/fluidbox.min.css"
          integrity="sha512-1gVXQF5Q9gL1HvHBLK0y3IAWCorLY9EU+JMTsLBlXgWfgf6EIS/8B27R/nUq1joeKz2N7ZHCNnLCjc+PuqDqDA=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.css"
          integrity="sha512-UTNP5BXLIptsaj5WdKFrkFov94lDx+eBvbKyoe1YAfjeRPC+gT5kyZ10kOHCfNZqEui1sxmqvodNUx3KbuYI/A=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.css"
          integrity="sha512-yxWNfGm+7EK+hqP2CMJ13hsUNCQfHmOuCuLmOq2+uv/AVQtFAjlAJO8bHzpYGQnBghULqnPuY8NEr7f5exR3Qw=="
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/default-skin/default-skin.min.css"
          integrity="sha512-Rck8F2HFBjAQpszOB9Qy+NVLeIy4vUOMB7xrp46edxB3KXs2RxXRguHfrJqNK+vJ+CkfvcGqAKMJTyWYBiBsGA=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
          integrity="sha512-+EoPw+Fiwh6eSeRK7zwIKG2MA8i3rV/DGa3tdttQGgWyatG/SkncT53KHQaS5Jh9MNOT3dmFL0FjTY08And/Cw=="
          crossorigin="anonymous"/>


    <!-- INITIAL SCRIPTS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
            integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"
            integrity="sha512-3n19xznO0ubPpSwYCRRBgHh63DrV+bdZfHK52b1esvId4GsfwStQNPJFjeQos2h3JwCmZl0/LgLxSKMAI55hgw=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.2.1/jquery-migrate.min.js"
            integrity="sha512-fDGBclS3HUysEBIKooKWFDEWWORoA20n60OwY7OSYgxGEew9s7NgDaPkj7gqQcVXnASPvZAiFW8DiytstdlGtQ=="
            crossorigin="anonymous"></script>


    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <link rel="stylesheet"
          href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css"
          integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{% static 'css/768.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/992.css' %}">


    <!-- InstanceBeginEditable name="head" -->
    <!-- InstanceEndEditable -->


</head>

<body>

<!-- page -->
<div id="page" class="hfeed site">

    <!-- header -->
    <header id="masthead" class="site-header" role="banner">


        <!-- site-logo -->
        <div class="site-logo">


            <!-- logo : image -->
            <h1 class="site-title">
                <a href="{% url 'core:home' %}" rel="home">
                    <img src="{% static 'logo black.png' %}" alt="logo">
                </a>
            </h1>
            <!-- logo : image -->

        </div>
        <!-- site-logo -->


        <!-- site-navigation -->
        <nav id="primary-navigation" class="site-navigation primary-navigation" role="navigation">

            <a class="menu-toggle"><span class="lines"></span></a>

            <!-- nav-menu -->
            <div class="nav-menu">
                <ul>
                    <li>
                        <a href="{% url 'core:home' %}">HOME</a>
                    </li>
                    <li>
                        <a href="{% url 'core:portfolio' %}">PORTFOLIO</a>
                    </li>
                    <li><a href="{% url 'core:price' %}">PRICING</a></li>
                    <li><a href="{% url 'core:about' %}">ABOUT ME</a>
                        <!-- level 2 -->
                        <!-- level 2 -->
                    </li>
                    <li><a href="{% url 'core:contact' %}">CONTACT</a></li>
                </ul>
            </div>
            <!-- nav-menu -->

        </nav>
        <!-- site-navigation -->


    </header>
    <!-- header -->


    <!-- site-main -->
    <div id="main" class="site-main">


        <!-- primary -->
        <div id="primary" class="content-area">

            <!-- site-content -->
            <div id="content" class="site-content" role="main">

                <!-- layout-full -->
                {% block content %}

                {% endblock %}
                <!-- layout-full -->

            </div>
            <!-- site-content -->

        </div>
        <!-- primary -->


    </div>
    <!-- site-main -->

    <br>
    <div class="container">
        <div class="site-footer">
            <hr style="font-weight: 100">


            <div class="owl-carousel owl-loading" data-items="5" data-loop="true" data-center="true"
                 data-mouse-drag="true" data-nav="true" data-dots="false" data-autoplay="true"
                 data-autoplay-speed="500" data-autoplay-timeout="3000">
                {#                data-nav-text-prev="prev"#}
                {#                 data-nav-text-next="next">#}
{#                <span class="entry-title">thelittphotographer Instagram Feed</span>#}
                                {% instagram_user_recent_media thelittphotographer %}
                                {% for media in recent_media %}
                                    <div>
                                        <a href="//instagram.com/p/{{ media.shortcode }}" target="_blank">
                                            <i class="instagram"></i>
                                            <img src="{{ media.thumbnail_src }}" alt="slide">
                                        </a>
                                    </div>
                                {% endfor %}

            </div>

        </div>
    </div>

    <!-- site-footer -->
    <footer id="colophon" class="site-footer" role="contentinfo">

        <!-- layout-medium -->
        <div class="layout-medium">

            <!-- footer-social -->
            <div class="footer-social">

                <ul class="social">
                    <li><a class="facebook" href="#"></a></li>
                    <li><a class="twitter" href="#"></a></li>
                    <li><a class="instagram" href="//instagram.com/p/thelittphotographer"></a></li>
                </ul>

            </div>
            <!-- footer-social -->


            <!-- .site-info -->
            <div class="site-info">

                <p>Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    Bob Smith
                </p>

            </div>
            <!-- .site-info -->


        </div>
        <!-- layout-medium -->


    </footer>
    <!-- site-footer -->


</div>
<!-- page -->
<div class="offset"></div>
<!-- /.container -->

<!-- SCRIPTS -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/fluidbox/2.0.5/js/jquery.fluidbox.min.js"
        integrity="sha512-0kQqdmb3fpKtRwrbCZDlmiwuZgDyPAOLDOu/HyAt4py7lAVDXKknqtqS6dFNV8U8JrHZymQxlO9SFPZ2u8dhMw=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.js"
        integrity="sha512-IUpSKpPKlXuPokiYONEZUG/H4c1rw4VmbGdnBKB18qm/9jbnxQ4Rv5Da9qEmB3hIa3k4DxRNoZfB6FTpERnuOQ=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
        integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.js"
        integrity="sha512-2R4VJGamBudpzC1NTaSkusXP7QkiUYvEKhpJAxeVCqLDsgW4OqtzorZGpulE3eEA7p++U0ZYmqBwO3m+R2hRjA=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe-ui-default.min.js"
        integrity="sha512-SxO0cwfxj/QhgX1SgpmUr0U2l5304ezGVhc0AO2YwOQ/C8O67ynyTorMKGjVv1fJnPQgjdxRz6x70MY9r0sKtQ=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"
        integrity="sha512-IsNh5E3eYy3tr/JiX2Yx4vsCujtkhwl7SLqgnwLNgf04Hrt9BT9SXlLlZlWx+OK4ndzAoALhsMNcCmkggjZB1w=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slippry/1.4.0/slippry.min.js"
        integrity="sha512-AuA2kbI9ByrbsuXrrdqY8qlayz6cFSwLl7qvLBQSMJIWJ5YFjBRKrtVWD3NKWZHOcxqpnqYJtcLaZARXxR+Kjg=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/collageplus/0.3.3/jquery.collagePlus.min.js"
        integrity="sha512-dZbysZg9ikJMFBQALYbNeY3YIfKLjavLCtoiKve+NhUFDjVU5YqhT4KsiSLaPKRy4p7QuneQhXH2Mzb+R8KwQw=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js"
        integrity="sha512-S5PZ9GxJZO16tT9r3WJp/Safn31eu8uWrzglMahDT4dsmgqWonRY9grk3j+3tfuPr9WJNsfooOR7Gi7HL5W2jw=="
        crossorigin="anonymous"></script>

<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js"
        integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"
        integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9"
        crossorigin="anonymous"></script>

<script src="{% static 'js/main.js' %}"></script>


</body>
<!-- InstanceEnd -->
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block link %}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'js/jquery.fluidbox/fluidbox.css' %}">#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'js/owl-carousel/owl.carousel.css' %}">#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'js/photo-swipe/photoswipe.css' %}">#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'js/photo-swipe/default-skin/default-skin.css' %}">#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'js/jquery.magnific-popup/magnific-popup.css' %}">#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'js/slippry/slippry.css' %}">#}
    {#<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">#}

{% endblock %}
{% block title %}
    Contact
{% endblock %}
{% block content %}

    <div class="container">
        <div class="card">
            <div class="col-lg-12  ">
                <div class="main-wrap">
                    <div class="section" data-aos="fade-up">
{#                        <div class="container">#}
                            <div class="card-header bg-secondary">

                                <div class="row justify-content-center mb-3">
                                    <div class="col-md-8  text-center">
                                        <h2 class="site-title">Contact Form</h2>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">

                                <div class="row justify-content-center">
                                    <div class="col-md-10 p-5 form-wrap">
                                        <form method="POST">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <label for="id_name">Name</label>
                                                            <input type="text" name="name" class="form-control"
                                                                   placeholder="Name"
                                                                   title=""
                                                                   required="" id="id_name">
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6">
                                                        <div class="form-group ">
                                                            <label for="id_email">email</label>
                                                            <input type="email" name="email" class="form-control"
                                                                   placeholder="From email"
                                                                   title=""
                                                                   required=required
                                                                   id="id_email">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            <label for="id_subject">Subject</label>
                                                            <input type="text" name="subject" class="form-control"
                                                                   placeholder="Subject"
                                                                   title=""
                                                                   required=required
                                                                   id="id_subject">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            <label for="id_message">Message</label>
                                                            <textarea name="message"
                                                                      cols="2" rows="2"
                                                                      placeholder="Enter the Message here"
                                                                      class=""
                                                                      title=""
                                                                      required=required
                                                                      id="id_message"
                                                                      spellcheck="false"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            {#                                <button class="btn btn-outline-primary ">ADD</button>#}
                                                            <button type="submit" class=" button">Send
                                                                Message
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        {#                <form method="POST">#}
                                        {#                    {% csrf_token %}#}
                                        {#                    {% bootstrap_form form %}#}
                                        {#                    {% buttons %}#}
                                        {#                        <button type="submit" class="btn btn-primary">Send Message</button>#}
                                        {#                    {% endbuttons %}#}
                                        {#                </form>#}
                                    </div>
                                </div>
                            </div>
                        <div class="card-footer ">
                        <div class="contact_info_icon comments-title" style="size: 200px">
                            <a href="https://instagram.com/thelittphotographer" class="float-left"
                               style="margin: 0 ; color: black"><i class="pw-icon-instagram"></i>thelittphotographer</a>
                            <a href="tel:‭234 706 394 7753" class="text-center" style="margin: 0 20%; color: black"><i
                                    class="pw-icon-phone-outline"></i>+‭234 706 394 7753</a>
                            <a href="mailto:Thelittphotographer@gmail.com" class="float-right"
                               style="margin: 0 ; color: black"><i
                                    class="pw-icon-mail"></i>Thelittphotographer@gmail.com</a>

                        </div>
                    </div>
{#                        </div>#}
                    </div> <!-- .section -->


                    <div class="map-wrap" id="map" data-aos="fade"></div>


                </div> <!-- .main-wrap -->
            </div>
        </div>
    </div>


{% endblock %}
{% block script %}
    {#<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>#}
    {#<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>#}
    {#<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>#}
    {#    <script src="{% static 'js/fastclick.js' %}"></script>#}
    {#    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>#}
    {#    <script src="{% static 'js/owl-carousel/owl.carousel.min.js' %}"></script>#}
    {#    <script src="{% static 'js/jquery.collagePlus/jquery.collagePlus.min.js' %}"></script>#}
    {#    <script src="{% static 'js/jquery.magnific-popup/jquery.magnific-popup.min.js' %}"></script>#}
    {##}
    {#    <script src="{% static 'js/main.js' %}"></script>#}
    {#    <script src="{% static 'js/jquery.fluidbox/jquery.fluidbox.min.js' %}"></script>#}
{% endblock %}

templates/portfolio.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
Portfolio
{% endblock %}
{% block link %}
{#    <link rel="stylesheet" type="text/css" href="{% static 'js/jquery.fluidbox/fluidbox.css' %}">#}
{#<link rel="stylesheet" type="text/css" href="{% static 'js/owl-carousel/owl.carousel.css' %}">#}
{#<link rel="stylesheet" type="text/css" href="{% static 'js/photo-swipe/photoswipe.css' %}">#}
{#<link rel="stylesheet" type="text/css" href="{% static 'js/photo-swipe/default-skin/default-skin.css' %}">#}
{#<link rel="stylesheet" type="text/css" href="{% static 'js/jquery.magnific-popup/magnific-popup.css' %}">#}
{#<link rel="stylesheet" type="text/css" href="{% static 'js/slippry/slippry.css' %}">#}

{% endblock %}
{% block content %}
    <div class="layout-full">




        <hr>

        <!-- .gallery-single -->
        <div class="gallery-single">


            <!-- entry-header -->
            <header class="entry-header">
                <h1 class="entry-title">CATEGORY</h1>
            </header>
            <!-- entry-header -->


            <!-- .media-grid-wrap -->
            <div class="media-grid-wrap">

                <!-- .pw-gallery -->
{#                <div class="mfp-gallery pw-collage pw-collage-loading" data-row-height="360"#}
{#                     data-mobile-row-height="120" data-effect="effect-4">#}

                    <div class="gallery-grid">


                        {% for cat,img in zipped %}

                            <!-- gallery-item -->
                            <div class="masonry-item">
                                <figure>
                                    {% thumbnail img.image "500x500" crop="center" as im %}
                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="category-post">
                                {% endthumbnail %}
                                    <figcaption>
                                        <h2 style="color: #0f6674">{{ cat.name }}</h2>
                                        <a href="{% url 'core:category_detail' cat.slug %}">View more</a>
                                    </figcaption>
                                </figure>
                            </div>
                            <!-- gallery-item -->
                        {% endfor %}


                    </div>

                    <!-- .pw-gallery -->

                <!-- .media-grid-wrap -->

            </div>
            <!-- .gallery-single -->

         <nav class="nav-single row">
&nbsp;&nbsp;&nbsp;
                    <div class="nav-next col-xs-6">
                        <h4>VIEW MORE</h4>
                        <a href="{% url 'core:category' %}" rel="next">CATEGORY <span
                                class="meta-nav">→</span></a>
                    </div>

                </nav>

            <!-- InstanceEndEditable -->

        </div>
        <hr>
    <div class="gallery-single">


            <!-- entry-header -->
            <header class="entry-header">
                <h1 class="entry-title">ALBUM</h1>
            </header>
            <!-- entry-header -->


            <!-- .media-grid-wrap -->
            <div class="media-grid-wrap">

                <!-- .pw-gallery -->
{#                <div class="mfp-gallery pw-collage pw-collage-loading" data-row-height="360"#}
{#                     data-mobile-row-height="120" data-effect="effect-4">#}

                    <div class="gallery-grid">


                        {% for al,img in zipped2 %}

                            <!-- gallery-item -->
                            <div class="masonry-item">
                                <figure>
                                    {% thumbnail img.image "400x450" crop="center" as im %}
                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="category-post">
                                {% endthumbnail %}
                                    {#                                        {% for foo in t %}#}
{#                                    <img src="{{ img.image.url }}" alt="gallery-post"/>#}
                                    {#                                        {% endfor %}#}
                                    <figcaption>
                                        <h2 style="color: #0f6674; font-family: 'Roboto Light',serif">{{ al.name }}</h2>
                                        <a href="{% url 'core:album_detail' al.slug %}">View more</a>
                                    </figcaption>
                                </figure>
                            </div>
                            <!-- gallery-item -->
                        {% endfor %}


                    </div>

                    <!-- .pw-gallery -->

                <!-- .media-grid-wrap -->

            </div>
            <!-- .gallery-single -->
    <nav class="nav-single row">
&nbsp;&nbsp;&nbsp;
                    <div class="nav-next col-xs-6 pull-left">
                        <h4>VIEW MORE </h4>
                        <a href="{% url 'core:album' %}" rel="next">ALBUM <span
                                class="meta-nav">→</span></a>
                    </div>

                </nav>


            <!-- InstanceEndEditable -->


        </div>

    </div>
{% endblock %}

{% block script %}

{#    <script src="{% static 'js/fastclick.js' %}"></script>#}
{#    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>#}
{#    <script src="{% static 'js/owl-carousel/owl.carousel.min.js' %}"></script>#}
{#    <script src="{% static 'js/jquery.collagePlus/jquery.collagePlus.min.js' %}"></script>#}
{#    <script src="{% static 'js/jquery.magnific-popup/jquery.magnific-popup.min.js' %}"></script>#}
{#    <script src="{% static 'js/main.js' %}"></script>#}
{#    <script src="{% static 'js/jquery.fluidbox/jquery.fluidbox.min.js' %}"></script>#}

{% endblock %}